### ISSUE TITLE
Simple `se.search` not currently working

### ISSUE THREAD

**Issue by milesmcc** [gitronald/WebSearcher#21]
I haven't been able to dive deep into this issue yet, so apologies if this is user error. I can look into contributing a fix. In the meantime, I ran into an error while doing a simple `se.search("test")` and `se.parse_results()`:

```python
import WebSearcher as ws
se = ws.SearchEngine()

se.search("test")
# 2021-11-19 09:59:41,825 | 174380 | INFO | WebSearcher.searchers | 200 | test

se.parse_results()
# 2021-11-19 09:59:43,659 | 174380 | ERROR | WebSearcher.searchers | Parsing error | serp_id : 90a3ed9e32b2aaf4c61c410eb925426119e1a9dc53d4286ade99a809
```

Traceback:
```
Traceback (most recent call last):
  File "/home/miles/.local/lib/python3.9/site-packages/WebSearcher/searchers.py", line 237, in parse_results
    self.results = parsers.parse_serp(soup, serp_id=self.serp_id)
  File "/home/miles/.local/lib/python3.9/site-packages/WebSearcher/parsers.py", line 210, in parse_serp
    cmpts = extract_components(soup)
  File "/home/miles/.local/lib/python3.9/site-packages/WebSearcher/parsers.py", line 133, in extract_components
    column = extract_results_column(soup)
  File "/home/miles/.local/lib/python3.9/site-packages/WebSearcher/parsers.py", line 56, in extract_results_column
    column = [('main', c) for c in rso.children if c.name not in drop_tags]
AttributeError: 'NoneType' object has no attribute 'children'
```

(Done from a residential IP address, if it matters.)

**Comment by gitronald** [comment]
Should be good now, see https://github.com/gitronald/WebSearcher/issues/23 for more details on the fix I applied.
